'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace serviciocfe
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ReqBody", [Namespace]:="http://www.uruware.com/ucfe/inbox/webservice"),  _
     System.SerializableAttribute()>  _
    Partial Public Class ReqBody
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private HMACField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ReqField As serviciocfe.RequerimientoParaUcfe
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private RequestDateField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ToutField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ReqEncField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CodComercioField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CodTerminalField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property HMAC() As String
            Get
                Return Me.HMACField
            End Get
            Set
                If (Object.ReferenceEquals(Me.HMACField, value) <> true) Then
                    Me.HMACField = value
                    Me.RaisePropertyChanged("HMAC")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Req() As serviciocfe.RequerimientoParaUcfe
            Get
                Return Me.ReqField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ReqField, value) <> true) Then
                    Me.ReqField = value
                    Me.RaisePropertyChanged("Req")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property RequestDate() As String
            Get
                Return Me.RequestDateField
            End Get
            Set
                If (Object.ReferenceEquals(Me.RequestDateField, value) <> true) Then
                    Me.RequestDateField = value
                    Me.RaisePropertyChanged("RequestDate")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Tout() As Integer
            Get
                Return Me.ToutField
            End Get
            Set
                If (Me.ToutField.Equals(value) <> true) Then
                    Me.ToutField = value
                    Me.RaisePropertyChanged("Tout")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=4)>  _
        Public Property ReqEnc() As String
            Get
                Return Me.ReqEncField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ReqEncField, value) <> true) Then
                    Me.ReqEncField = value
                    Me.RaisePropertyChanged("ReqEnc")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=5)>  _
        Public Property CodComercio() As String
            Get
                Return Me.CodComercioField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CodComercioField, value) <> true) Then
                    Me.CodComercioField = value
                    Me.RaisePropertyChanged("CodComercio")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=6)>  _
        Public Property CodTerminal() As String
            Get
                Return Me.CodTerminalField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CodTerminalField, value) <> true) Then
                    Me.CodTerminalField = value
                    Me.RaisePropertyChanged("CodTerminal")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="RequerimientoParaUcfe", [Namespace]:="http://www.uruware.com/ucfe/inbox/webservice"),  _
     System.SerializableAttribute()>  _
    Partial Public Class RequerimientoParaUcfe
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AdendaField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CertificadoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CfeXmlOTextoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CifrarComplementoFiscalField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CodComercioField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CodRtaField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CodTerminalField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DatosQrField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EmailEnvioPdfReceptorField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EstadoSituacionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FechaReqField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private HoraReqField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdReqField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ImpresoraField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NumeroCfeField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private RechComField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private RutEmisorField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SerieField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TipoCfeField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TipoMensajeField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TipoNotificacionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UuidField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Adenda() As String
            Get
                Return Me.AdendaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AdendaField, value) <> true) Then
                    Me.AdendaField = value
                    Me.RaisePropertyChanged("Adenda")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Certificado() As String
            Get
                Return Me.CertificadoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CertificadoField, value) <> true) Then
                    Me.CertificadoField = value
                    Me.RaisePropertyChanged("Certificado")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CfeXmlOTexto() As String
            Get
                Return Me.CfeXmlOTextoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CfeXmlOTextoField, value) <> true) Then
                    Me.CfeXmlOTextoField = value
                    Me.RaisePropertyChanged("CfeXmlOTexto")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CifrarComplementoFiscal() As String
            Get
                Return Me.CifrarComplementoFiscalField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CifrarComplementoFiscalField, value) <> true) Then
                    Me.CifrarComplementoFiscalField = value
                    Me.RaisePropertyChanged("CifrarComplementoFiscal")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CodComercio() As String
            Get
                Return Me.CodComercioField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CodComercioField, value) <> true) Then
                    Me.CodComercioField = value
                    Me.RaisePropertyChanged("CodComercio")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CodRta() As String
            Get
                Return Me.CodRtaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CodRtaField, value) <> true) Then
                    Me.CodRtaField = value
                    Me.RaisePropertyChanged("CodRta")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CodTerminal() As String
            Get
                Return Me.CodTerminalField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CodTerminalField, value) <> true) Then
                    Me.CodTerminalField = value
                    Me.RaisePropertyChanged("CodTerminal")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DatosQr() As String
            Get
                Return Me.DatosQrField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DatosQrField, value) <> true) Then
                    Me.DatosQrField = value
                    Me.RaisePropertyChanged("DatosQr")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property EmailEnvioPdfReceptor() As String
            Get
                Return Me.EmailEnvioPdfReceptorField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EmailEnvioPdfReceptorField, value) <> true) Then
                    Me.EmailEnvioPdfReceptorField = value
                    Me.RaisePropertyChanged("EmailEnvioPdfReceptor")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property EstadoSituacion() As String
            Get
                Return Me.EstadoSituacionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EstadoSituacionField, value) <> true) Then
                    Me.EstadoSituacionField = value
                    Me.RaisePropertyChanged("EstadoSituacion")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FechaReq() As String
            Get
                Return Me.FechaReqField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FechaReqField, value) <> true) Then
                    Me.FechaReqField = value
                    Me.RaisePropertyChanged("FechaReq")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property HoraReq() As String
            Get
                Return Me.HoraReqField
            End Get
            Set
                If (Object.ReferenceEquals(Me.HoraReqField, value) <> true) Then
                    Me.HoraReqField = value
                    Me.RaisePropertyChanged("HoraReq")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IdReq() As String
            Get
                Return Me.IdReqField
            End Get
            Set
                If (Object.ReferenceEquals(Me.IdReqField, value) <> true) Then
                    Me.IdReqField = value
                    Me.RaisePropertyChanged("IdReq")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Impresora() As String
            Get
                Return Me.ImpresoraField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ImpresoraField, value) <> true) Then
                    Me.ImpresoraField = value
                    Me.RaisePropertyChanged("Impresora")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property NumeroCfe() As String
            Get
                Return Me.NumeroCfeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NumeroCfeField, value) <> true) Then
                    Me.NumeroCfeField = value
                    Me.RaisePropertyChanged("NumeroCfe")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property RechCom() As String
            Get
                Return Me.RechComField
            End Get
            Set
                If (Object.ReferenceEquals(Me.RechComField, value) <> true) Then
                    Me.RechComField = value
                    Me.RaisePropertyChanged("RechCom")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property RutEmisor() As String
            Get
                Return Me.RutEmisorField
            End Get
            Set
                If (Object.ReferenceEquals(Me.RutEmisorField, value) <> true) Then
                    Me.RutEmisorField = value
                    Me.RaisePropertyChanged("RutEmisor")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Serie() As String
            Get
                Return Me.SerieField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SerieField, value) <> true) Then
                    Me.SerieField = value
                    Me.RaisePropertyChanged("Serie")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property TipoCfe() As String
            Get
                Return Me.TipoCfeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TipoCfeField, value) <> true) Then
                    Me.TipoCfeField = value
                    Me.RaisePropertyChanged("TipoCfe")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property TipoMensaje() As Integer
            Get
                Return Me.TipoMensajeField
            End Get
            Set
                If (Me.TipoMensajeField.Equals(value) <> true) Then
                    Me.TipoMensajeField = value
                    Me.RaisePropertyChanged("TipoMensaje")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property TipoNotificacion() As String
            Get
                Return Me.TipoNotificacionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TipoNotificacionField, value) <> true) Then
                    Me.TipoNotificacionField = value
                    Me.RaisePropertyChanged("TipoNotificacion")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Uuid() As String
            Get
                Return Me.UuidField
            End Get
            Set
                If (Object.ReferenceEquals(Me.UuidField, value) <> true) Then
                    Me.UuidField = value
                    Me.RaisePropertyChanged("Uuid")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="RespBody", [Namespace]:="http://schemas.datacontract.org/2004/07/Uruware.Ucfe.Inbox.WebService"),  _
     System.SerializableAttribute()>  _
    Partial Public Class RespBody
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ErrorCodeField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ErrorMessageField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private RespField As serviciocfe.RespuestaDeUcfe
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private RespEncField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ErrorCode() As Integer
            Get
                Return Me.ErrorCodeField
            End Get
            Set
                If (Me.ErrorCodeField.Equals(value) <> true) Then
                    Me.ErrorCodeField = value
                    Me.RaisePropertyChanged("ErrorCode")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ErrorMessage() As String
            Get
                Return Me.ErrorMessageField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ErrorMessageField, value) <> true) Then
                    Me.ErrorMessageField = value
                    Me.RaisePropertyChanged("ErrorMessage")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Resp() As serviciocfe.RespuestaDeUcfe
            Get
                Return Me.RespField
            End Get
            Set
                If (Object.ReferenceEquals(Me.RespField, value) <> true) Then
                    Me.RespField = value
                    Me.RaisePropertyChanged("Resp")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property RespEnc() As String
            Get
                Return Me.RespEncField
            End Get
            Set
                If (Object.ReferenceEquals(Me.RespEncField, value) <> true) Then
                    Me.RespEncField = value
                    Me.RaisePropertyChanged("RespEnc")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="RespuestaDeUcfe", [Namespace]:="http://www.uruware.com/ucfe/inbox/webservice"),  _
     System.SerializableAttribute()>  _
    Partial Public Class RespuestaDeUcfe
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AdendaField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CaeNroDesdeField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CaeNroHastaField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CertificadoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CertificadoParaFirmarCfeField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ClaveCertificadoFirmaField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CodComercioField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CodRtaField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CodTerminalField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CodigoSeguridadField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DatosQrField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EstadoEnDgiCfeRecibidoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EstadoSituacionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EtiquetasField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FechaFirmaField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FechaReqField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private HoraReqField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdCaeField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdReqField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ImagenQrField() As Byte
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MensajeRtaField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NumeroCfeField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private RangoDesdeField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private RangoHastaField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private RutEmisorField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SerieField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TipoCfeField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TipoMensajeField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TipoNotificacionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UuidField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private VencimientoCaeField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private XmlCfeFirmadoField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Adenda() As String
            Get
                Return Me.AdendaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AdendaField, value) <> true) Then
                    Me.AdendaField = value
                    Me.RaisePropertyChanged("Adenda")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CaeNroDesde() As String
            Get
                Return Me.CaeNroDesdeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CaeNroDesdeField, value) <> true) Then
                    Me.CaeNroDesdeField = value
                    Me.RaisePropertyChanged("CaeNroDesde")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CaeNroHasta() As String
            Get
                Return Me.CaeNroHastaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CaeNroHastaField, value) <> true) Then
                    Me.CaeNroHastaField = value
                    Me.RaisePropertyChanged("CaeNroHasta")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Certificado() As String
            Get
                Return Me.CertificadoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CertificadoField, value) <> true) Then
                    Me.CertificadoField = value
                    Me.RaisePropertyChanged("Certificado")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CertificadoParaFirmarCfe() As String
            Get
                Return Me.CertificadoParaFirmarCfeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CertificadoParaFirmarCfeField, value) <> true) Then
                    Me.CertificadoParaFirmarCfeField = value
                    Me.RaisePropertyChanged("CertificadoParaFirmarCfe")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ClaveCertificadoFirma() As String
            Get
                Return Me.ClaveCertificadoFirmaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ClaveCertificadoFirmaField, value) <> true) Then
                    Me.ClaveCertificadoFirmaField = value
                    Me.RaisePropertyChanged("ClaveCertificadoFirma")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CodComercio() As String
            Get
                Return Me.CodComercioField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CodComercioField, value) <> true) Then
                    Me.CodComercioField = value
                    Me.RaisePropertyChanged("CodComercio")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CodRta() As String
            Get
                Return Me.CodRtaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CodRtaField, value) <> true) Then
                    Me.CodRtaField = value
                    Me.RaisePropertyChanged("CodRta")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CodTerminal() As String
            Get
                Return Me.CodTerminalField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CodTerminalField, value) <> true) Then
                    Me.CodTerminalField = value
                    Me.RaisePropertyChanged("CodTerminal")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CodigoSeguridad() As String
            Get
                Return Me.CodigoSeguridadField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CodigoSeguridadField, value) <> true) Then
                    Me.CodigoSeguridadField = value
                    Me.RaisePropertyChanged("CodigoSeguridad")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DatosQr() As String
            Get
                Return Me.DatosQrField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DatosQrField, value) <> true) Then
                    Me.DatosQrField = value
                    Me.RaisePropertyChanged("DatosQr")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property EstadoEnDgiCfeRecibido() As String
            Get
                Return Me.EstadoEnDgiCfeRecibidoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EstadoEnDgiCfeRecibidoField, value) <> true) Then
                    Me.EstadoEnDgiCfeRecibidoField = value
                    Me.RaisePropertyChanged("EstadoEnDgiCfeRecibido")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property EstadoSituacion() As String
            Get
                Return Me.EstadoSituacionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EstadoSituacionField, value) <> true) Then
                    Me.EstadoSituacionField = value
                    Me.RaisePropertyChanged("EstadoSituacion")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Etiquetas() As String
            Get
                Return Me.EtiquetasField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EtiquetasField, value) <> true) Then
                    Me.EtiquetasField = value
                    Me.RaisePropertyChanged("Etiquetas")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FechaFirma() As String
            Get
                Return Me.FechaFirmaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FechaFirmaField, value) <> true) Then
                    Me.FechaFirmaField = value
                    Me.RaisePropertyChanged("FechaFirma")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FechaReq() As String
            Get
                Return Me.FechaReqField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FechaReqField, value) <> true) Then
                    Me.FechaReqField = value
                    Me.RaisePropertyChanged("FechaReq")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property HoraReq() As String
            Get
                Return Me.HoraReqField
            End Get
            Set
                If (Object.ReferenceEquals(Me.HoraReqField, value) <> true) Then
                    Me.HoraReqField = value
                    Me.RaisePropertyChanged("HoraReq")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IdCae() As String
            Get
                Return Me.IdCaeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.IdCaeField, value) <> true) Then
                    Me.IdCaeField = value
                    Me.RaisePropertyChanged("IdCae")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IdReq() As String
            Get
                Return Me.IdReqField
            End Get
            Set
                If (Object.ReferenceEquals(Me.IdReqField, value) <> true) Then
                    Me.IdReqField = value
                    Me.RaisePropertyChanged("IdReq")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ImagenQr() As Byte()
            Get
                Return Me.ImagenQrField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ImagenQrField, value) <> true) Then
                    Me.ImagenQrField = value
                    Me.RaisePropertyChanged("ImagenQr")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property MensajeRta() As String
            Get
                Return Me.MensajeRtaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.MensajeRtaField, value) <> true) Then
                    Me.MensajeRtaField = value
                    Me.RaisePropertyChanged("MensajeRta")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property NumeroCfe() As String
            Get
                Return Me.NumeroCfeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NumeroCfeField, value) <> true) Then
                    Me.NumeroCfeField = value
                    Me.RaisePropertyChanged("NumeroCfe")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property RangoDesde() As String
            Get
                Return Me.RangoDesdeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.RangoDesdeField, value) <> true) Then
                    Me.RangoDesdeField = value
                    Me.RaisePropertyChanged("RangoDesde")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property RangoHasta() As String
            Get
                Return Me.RangoHastaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.RangoHastaField, value) <> true) Then
                    Me.RangoHastaField = value
                    Me.RaisePropertyChanged("RangoHasta")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property RutEmisor() As String
            Get
                Return Me.RutEmisorField
            End Get
            Set
                If (Object.ReferenceEquals(Me.RutEmisorField, value) <> true) Then
                    Me.RutEmisorField = value
                    Me.RaisePropertyChanged("RutEmisor")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Serie() As String
            Get
                Return Me.SerieField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SerieField, value) <> true) Then
                    Me.SerieField = value
                    Me.RaisePropertyChanged("Serie")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property TipoCfe() As String
            Get
                Return Me.TipoCfeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TipoCfeField, value) <> true) Then
                    Me.TipoCfeField = value
                    Me.RaisePropertyChanged("TipoCfe")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property TipoMensaje() As Integer
            Get
                Return Me.TipoMensajeField
            End Get
            Set
                If (Me.TipoMensajeField.Equals(value) <> true) Then
                    Me.TipoMensajeField = value
                    Me.RaisePropertyChanged("TipoMensaje")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property TipoNotificacion() As String
            Get
                Return Me.TipoNotificacionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TipoNotificacionField, value) <> true) Then
                    Me.TipoNotificacionField = value
                    Me.RaisePropertyChanged("TipoNotificacion")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Uuid() As String
            Get
                Return Me.UuidField
            End Get
            Set
                If (Object.ReferenceEquals(Me.UuidField, value) <> true) Then
                    Me.UuidField = value
                    Me.RaisePropertyChanged("Uuid")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property VencimientoCae() As String
            Get
                Return Me.VencimientoCaeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.VencimientoCaeField, value) <> true) Then
                    Me.VencimientoCaeField = value
                    Me.RaisePropertyChanged("VencimientoCae")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property XmlCfeFirmado() As String
            Get
                Return Me.XmlCfeFirmadoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.XmlCfeFirmadoField, value) <> true) Then
                    Me.XmlCfeFirmadoField = value
                    Me.RaisePropertyChanged("XmlCfeFirmado")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://www.uruware.com/ucfe/inbox/webservice", ConfigurationName:="serviciocfe.ICfeService")>  _
    Public Interface ICfeService
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.uruware.com/ucfe/inbox/webservice/ICfeService/Invoke", ReplyAction:="http://www.uruware.com/ucfe/inbox/webservice/ICfeService/InvokeResponse")>  _
        Function Invoke(ByVal req As serviciocfe.ReqBody) As serviciocfe.RespBody
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface ICfeServiceChannel
        Inherits serviciocfe.ICfeService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class CfeServiceClient
        Inherits System.ServiceModel.ClientBase(Of serviciocfe.ICfeService)
        Implements serviciocfe.ICfeService
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function Invoke(ByVal req As serviciocfe.ReqBody) As serviciocfe.RespBody Implements serviciocfe.ICfeService.Invoke
            Return MyBase.Channel.Invoke(req)
        End Function
    End Class
End Namespace
